// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && ebpf

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NlpBackend struct {
	_       structs.HostLayout
	Ip4     uint32
	Port    uint16
	Healthy uint8
	Pad     uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	NlpMapBackends        = "backends"
	NlpMapRrCursor        = "rr_cursor"
	NlpMapSelfCgid        = "self_cgid"
	NlpProgCgroupConnect4 = "cgroup_connect4"
	NlpVarBackendCount    = "backend_count"
	NlpVarInterceptPort   = "intercept_port"
)

// LoadNlp returns the embedded CollectionSpec for Nlp.
func LoadNlp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NlpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Nlp: %w", err)
	}

	return spec, err
}

// LoadNlpObjects loads Nlp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NlpObjects
//	*NlpPrograms
//	*NlpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNlpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNlp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NlpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NlpSpecs struct {
	NlpProgramSpecs
	NlpMapSpecs
	NlpVariableSpecs
}

// NlpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NlpProgramSpecs struct {
	CgroupConnect4 *ebpf.ProgramSpec `ebpf:"cgroup_connect4"`
}

// NlpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NlpMapSpecs struct {
	Backends *ebpf.MapSpec `ebpf:"backends"`
	RrCursor *ebpf.MapSpec `ebpf:"rr_cursor"`
	SelfCgid *ebpf.MapSpec `ebpf:"self_cgid"`
}

// NlpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NlpVariableSpecs struct {
	BackendCount  *ebpf.VariableSpec `ebpf:"backend_count"`
	InterceptPort *ebpf.VariableSpec `ebpf:"intercept_port"`
}

// NlpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNlpObjects or ebpf.CollectionSpec.LoadAndAssign.
type NlpObjects struct {
	NlpPrograms
	NlpMaps
	NlpVariables
}

func (o *NlpObjects) Close() error {
	return _NlpClose(
		&o.NlpPrograms,
		&o.NlpMaps,
	)
}

// NlpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNlpObjects or ebpf.CollectionSpec.LoadAndAssign.
type NlpMaps struct {
	Backends *ebpf.Map `ebpf:"backends"`
	RrCursor *ebpf.Map `ebpf:"rr_cursor"`
	SelfCgid *ebpf.Map `ebpf:"self_cgid"`
}

func (m *NlpMaps) Close() error {
	return _NlpClose(
		m.Backends,
		m.RrCursor,
		m.SelfCgid,
	)
}

// NlpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNlpObjects or ebpf.CollectionSpec.LoadAndAssign.
type NlpVariables struct {
	BackendCount  *ebpf.Variable `ebpf:"backend_count"`
	InterceptPort *ebpf.Variable `ebpf:"intercept_port"`
}

// NlpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNlpObjects or ebpf.CollectionSpec.LoadAndAssign.
type NlpPrograms struct {
	CgroupConnect4 *ebpf.Program `ebpf:"cgroup_connect4"`
}

func (p *NlpPrograms) Close() error {
	return _NlpClose(
		p.CgroupConnect4,
	)
}

func _NlpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nlp_bpfel.o
var _NlpBytes []byte
